### PR TITLE
refactor: use more pattern matching

### PR DESCRIPTION
**Pull request by scarf005**
also bumped ts-pattern and typescript to latest.

### CODE REVIEW

**Comment by astahmer** [comment]
seems like the lockfile is outdated, other than that if the tests pass, LGTM 👍 

```
@github-actions
CI / Build (16.x) (pull_request) Failing after 7s
```

```sh
Run pnpm install --frozen-lockfile
Scope: all [6](https://github.com/astahmer/openapi-zod-client/actions/runs/5423160262/jobs/9861017512?pr=165#step:5:7) workspace projects
 ERR_PNPM_LOCKFILE_CONFIG_MISMATCH  Cannot proceed with the frozen installation. The current "settings.autoInstallPeers" configuration doesn't match the value found in the lockfile

Update your lockfile using "pnpm install --no-frozen-lockfile"
Error: Process completed with exit code 1.
```

**Comment by scarf005** [comment]
image

I think this is due to pnpm version mismatch from my local machine and CI environment.

related: https://github.com/orgs/pnpm/discussions/6633#discussioncomment-6082493

https://github.com/astahmer/openapi-zod-client/blob/e1737ddd1383b50f8e0950fe88364edc76353af0/.github/workflows/ci.yml#L34-L37

```
 ~/r/l/openapi-zod-client   pattern-match  lib  pnpm install --frozen-lockfile
Scope: all 6 workspace projects
.. postinstall$ preconstruct dev
│ 🎁 info project is valid!
│ 🎁 success created links!
└─ Done in 286ms
Done in 1.2s
 ~/r/l/openapi-zod-client   pattern-match  lib  cd ..
 ~/r/l/openapi-zod-client   pattern-match …  pnpm install --no-frozen-lockfile
Scope: all 6 workspace projects
Lockfile is up to date, resolution step is skipped
Already up to date
. postinstall$ preconstruct dev
│ 🎁 info project is valid!
│ 🎁 success created links!
└─ Done in 268ms
Done in 1.2s

pnpm --version
8.6.1
```

CI uses pnpm V7 wheras i use V8. Should i downgrade my local pnpm and update the lockfile?

**Comment by scarf005** [comment]
image

https://pnpm.io/installation#compatibility
looks like it'll be safe to bump CI to pnpm V8. I'll try updating the version and check if it breaks anything.

**Comment by astahmer** [comment]
yup, upgrading should be fine, thanks !

**Pull request merged**
