### PR TITLE
Fix generation with group-strategy any-file & ref variable not declared in schema

### PR DESCRIPTION
**Pull request by hou5emd**
This PR fix api generation when fef variable not declared in schema
Screenshot_20230603_204234

### CODE REVIEW

**Comment by astahmer** [comment]
nice !
could you a dedicated test & a patch [changeset](https://github.com/changesets/changesets/blob/main/docs/intro-to-using-changesets.md) so I can merge it ?

**Comment by hou5emd** [comment]
> nice ! could you a dedicated test & a patch [changeset](https://github.com/changesets/changesets/blob/main/docs/intro-to-using-changesets.md) so I can merge it ?

Yes, i can.

**Comment by hou5emd** [comment]
https://github.com/astahmer/openapi-zod-client/pull/251

**Comment by hou5emd** [comment]
@ezze close this bug in 251

**Pull request closed without merging**
